version: '3'
services:
  neo4j:
    container_name: neo4j
    hostname: neo4j
    image: 'neo4j'
    volumes:
      - './neo4j/data:/data'
      - './neo4j/logs:/logs'
      - './neo4j/import:/var/lib/neo4j/import'
      - './neo4j/plugins:/var/lib/neo4j/plugins'
      - './neo4j/conf:/var/lib/neo4j/conf'
    ports:
      - '7473:7473'
      - '7687:7687'
